const CONSTANTS = {
  categories_list: {
    CATEGORIES_LIST_REQUEST: "CATEGORIES_LIST_REQUEST",
    CATEGORIES_LIST_SUCCESS: "CATEGORIES_LIST_SUCCESS",
    CATEGORIES_LIST_FAILED: "CATEGORIES_LIST_FAILED",
  },
  joke: {
    USER_JOKE_REQUEST: "USER_JOKE_REQUEST",
    USER_JOKE_SUCCESS: "USER_JOKE_SUCCESS",
    USER_JOKE_FAILED: "USER_JOKE_FAILED",
    USER_JOKE_RESET: "USER_JOKE_RESET",
  },
};
export default CONSTANTS;
